---
swagger: "2.0"
info:
  description: "HTTP Endpoint backed by API Gateway and Lambda"
  version: "2022-04-08T11:56:06Z"
  title: "Human approval endpoint"
basePath: "/states"
schemes:
- "https"
paths:
  /execution:
    get:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: ${LAMBDA_INVOKE_ARN}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
