---
swagger: "2.0"
info:
  description: "HTTP Endpoint backed by API Gateway and Lambda"
  version: "2022-04-08T11:56:06Z"
  title: "Human approval endpoint"
basePath: "/states"
schemes:
- "https"
paths:
  /execution:
    get:
      consumes:
      - "application/json"
      responses:
        "302":
          description: "302 response"
          headers:
            Location:
              type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: ${LAMBDA_INVOKE_ARN}
        responses:
          default:
            statusCode: "302"
            responseParameters:
              method.response.header.Location: "integration.response.body.headers.Location"
        requestTemplates:
          application/json: "{\n  \"body\" : $input.json('$'),\n  \"headers\": {\n\
            \    #foreach($header in $input.params().header.keySet())\n    \"$header\"\
            : \"$util.escapeJavaScript($input.params().header.get($header))\" #if($foreach.hasNext),#end\n\
            \n    #end\n  },\n  \"method\": \"$context.httpMethod\",\n  \"params\"\
            : {\n    #foreach($param in $input.params().path.keySet())\n    \"$param\"\
            : \"$util.escapeJavaScript($input.params().path.get($param))\" #if($foreach.hasNext),#end\n\
            \n    #end\n  },\n  \"query\": {\n    #foreach($queryParam in $input.params().querystring.keySet())\n\
            \    \"$queryParam\": \"$util.escapeJavaScript($input.params().querystring.get($queryParam))\"\
            \ #if($foreach.hasNext),#end\n\n    #end\n  }  \n}\n"
        passthroughBehavior: "when_no_match"
        type: "aws"
